[2024-12-04 11:23:16,802] {processor.py:153} INFO - Started process (PID=3956) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:23:16,802] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:23:16,803] {logging_mixin.py:115} INFO - [2024-12-04 11:23:16,803] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:23:17,586] {logging_mixin.py:115} INFO - [2024-12-04 11:23:17,585] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:23:17,586] {logging_mixin.py:115} INFO - [2024-12-04 11:23:17,586] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:23:17,759] {logging_mixin.py:115} INFO - [2024-12-04 11:23:17,758] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:23:17,762] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:23:17,782] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.983 seconds
[2024-12-04 11:23:58,271] {processor.py:153} INFO - Started process (PID=4018) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:23:58,273] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:23:58,273] {logging_mixin.py:115} INFO - [2024-12-04 11:23:58,273] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:23:59,040] {logging_mixin.py:115} INFO - [2024-12-04 11:23:59,040] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:23:59,040] {logging_mixin.py:115} INFO - [2024-12-04 11:23:59,040] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:23:59,213] {logging_mixin.py:115} INFO - [2024-12-04 11:23:59,213] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:23:59,216] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:23:59,235] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.967 seconds
[2024-12-04 11:24:33,808] {processor.py:153} INFO - Started process (PID=4240) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:24:33,809] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:24:33,810] {logging_mixin.py:115} INFO - [2024-12-04 11:24:33,810] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:24:34,536] {logging_mixin.py:115} INFO - [2024-12-04 11:24:34,536] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:24:34,536] {logging_mixin.py:115} INFO - [2024-12-04 11:24:34,536] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:24:34,708] {logging_mixin.py:115} INFO - [2024-12-04 11:24:34,708] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:24:34,712] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:24:34,731] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.926 seconds
[2024-12-04 11:25:11,773] {processor.py:153} INFO - Started process (PID=4301) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:25:11,775] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:25:11,775] {logging_mixin.py:115} INFO - [2024-12-04 11:25:11,775] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:25:12,504] {logging_mixin.py:115} INFO - [2024-12-04 11:25:12,504] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:25:12,504] {logging_mixin.py:115} INFO - [2024-12-04 11:25:12,504] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:25:12,673] {logging_mixin.py:115} INFO - [2024-12-04 11:25:12,673] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:25:12,677] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:25:12,698] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.928 seconds
[2024-12-04 11:25:51,105] {processor.py:153} INFO - Started process (PID=4545) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:25:51,106] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:25:51,107] {logging_mixin.py:115} INFO - [2024-12-04 11:25:51,107] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:25:51,841] {logging_mixin.py:115} INFO - [2024-12-04 11:25:51,841] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:25:51,841] {logging_mixin.py:115} INFO - [2024-12-04 11:25:51,841] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:25:52,015] {logging_mixin.py:115} INFO - [2024-12-04 11:25:52,015] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:25:52,018] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:25:52,037] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.935 seconds
[2024-12-04 11:26:22,365] {processor.py:153} INFO - Started process (PID=4608) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:26:22,366] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:26:22,366] {logging_mixin.py:115} INFO - [2024-12-04 11:26:22,366] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:26:23,114] {logging_mixin.py:115} INFO - [2024-12-04 11:26:23,114] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:26:23,114] {logging_mixin.py:115} INFO - [2024-12-04 11:26:23,114] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:26:23,288] {logging_mixin.py:115} INFO - [2024-12-04 11:26:23,287] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:26:23,291] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:26:23,311] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.949 seconds
[2024-12-04 11:27:03,537] {processor.py:153} INFO - Started process (PID=4676) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:27:03,539] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:27:03,540] {logging_mixin.py:115} INFO - [2024-12-04 11:27:03,539] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:27:04,279] {logging_mixin.py:115} INFO - [2024-12-04 11:27:04,278] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:27:04,279] {logging_mixin.py:115} INFO - [2024-12-04 11:27:04,279] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:27:04,455] {logging_mixin.py:115} INFO - [2024-12-04 11:27:04,455] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:27:04,458] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:27:04,477] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.943 seconds
[2024-12-04 11:27:38,756] {processor.py:153} INFO - Started process (PID=4769) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:27:38,758] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:27:38,759] {logging_mixin.py:115} INFO - [2024-12-04 11:27:38,759] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:27:39,494] {logging_mixin.py:115} INFO - [2024-12-04 11:27:39,494] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:27:39,494] {logging_mixin.py:115} INFO - [2024-12-04 11:27:39,494] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:27:39,668] {logging_mixin.py:115} INFO - [2024-12-04 11:27:39,667] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:27:39,671] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:27:39,691] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.938 seconds
[2024-12-04 11:28:14,873] {processor.py:153} INFO - Started process (PID=4826) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:28:14,874] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:28:14,875] {logging_mixin.py:115} INFO - [2024-12-04 11:28:14,874] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:28:15,603] {logging_mixin.py:115} INFO - [2024-12-04 11:28:15,603] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:28:15,603] {logging_mixin.py:115} INFO - [2024-12-04 11:28:15,603] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:28:15,775] {logging_mixin.py:115} INFO - [2024-12-04 11:28:15,775] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:28:15,778] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:28:15,796] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.926 seconds
[2024-12-04 11:28:48,301] {processor.py:153} INFO - Started process (PID=4881) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:28:48,301] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:28:48,302] {logging_mixin.py:115} INFO - [2024-12-04 11:28:48,302] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:28:49,035] {logging_mixin.py:115} INFO - [2024-12-04 11:28:49,035] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:28:49,035] {logging_mixin.py:115} INFO - [2024-12-04 11:28:49,035] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:28:49,206] {logging_mixin.py:115} INFO - [2024-12-04 11:28:49,206] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:28:49,209] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:28:49,228] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.930 seconds
[2024-12-04 11:29:22,036] {processor.py:153} INFO - Started process (PID=4935) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:29:22,038] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:29:22,038] {logging_mixin.py:115} INFO - [2024-12-04 11:29:22,038] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:29:22,795] {logging_mixin.py:115} INFO - [2024-12-04 11:29:22,795] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:29:22,795] {logging_mixin.py:115} INFO - [2024-12-04 11:29:22,795] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:29:22,971] {logging_mixin.py:115} INFO - [2024-12-04 11:29:22,970] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:29:22,973] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:29:22,993] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.959 seconds
[2024-12-04 11:29:55,936] {processor.py:153} INFO - Started process (PID=4991) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:29:55,938] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:29:55,938] {logging_mixin.py:115} INFO - [2024-12-04 11:29:55,938] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:29:56,643] {logging_mixin.py:115} INFO - [2024-12-04 11:29:56,643] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:29:56,643] {logging_mixin.py:115} INFO - [2024-12-04 11:29:56,643] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:29:56,815] {logging_mixin.py:115} INFO - [2024-12-04 11:29:56,814] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:29:56,817] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:29:56,835] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.902 seconds
[2024-12-04 11:30:29,269] {processor.py:153} INFO - Started process (PID=5053) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:30:29,269] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:30:29,270] {logging_mixin.py:115} INFO - [2024-12-04 11:30:29,269] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:30:30,000] {logging_mixin.py:115} INFO - [2024-12-04 11:30:30,000] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:30:30,001] {logging_mixin.py:115} INFO - [2024-12-04 11:30:30,001] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:30:30,170] {logging_mixin.py:115} INFO - [2024-12-04 11:30:30,170] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:30:30,174] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:30:30,193] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.928 seconds
[2024-12-04 11:31:03,436] {processor.py:153} INFO - Started process (PID=5121) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:31:03,438] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:31:03,439] {logging_mixin.py:115} INFO - [2024-12-04 11:31:03,438] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:31:04,189] {logging_mixin.py:115} INFO - [2024-12-04 11:31:04,188] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:31:04,189] {logging_mixin.py:115} INFO - [2024-12-04 11:31:04,189] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:31:04,369] {logging_mixin.py:115} INFO - [2024-12-04 11:31:04,368] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:31:04,372] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:31:04,392] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.960 seconds
[2024-12-04 11:31:39,424] {processor.py:153} INFO - Started process (PID=5214) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:31:39,425] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:31:39,426] {logging_mixin.py:115} INFO - [2024-12-04 11:31:39,426] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:31:40,150] {logging_mixin.py:115} INFO - [2024-12-04 11:31:40,150] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:31:40,150] {logging_mixin.py:115} INFO - [2024-12-04 11:31:40,150] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:31:40,322] {logging_mixin.py:115} INFO - [2024-12-04 11:31:40,322] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:31:40,325] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:31:40,344] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.923 seconds
[2024-12-04 11:32:12,277] {processor.py:153} INFO - Started process (PID=5268) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:32:12,277] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:32:12,278] {logging_mixin.py:115} INFO - [2024-12-04 11:32:12,278] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:32:12,982] {logging_mixin.py:115} INFO - [2024-12-04 11:32:12,982] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:32:12,982] {logging_mixin.py:115} INFO - [2024-12-04 11:32:12,982] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:32:13,159] {logging_mixin.py:115} INFO - [2024-12-04 11:32:13,158] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:32:13,162] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:32:13,180] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.907 seconds
[2024-12-04 11:32:44,361] {processor.py:153} INFO - Started process (PID=5533) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:32:44,364] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:32:44,364] {logging_mixin.py:115} INFO - [2024-12-04 11:32:44,364] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:32:45,089] {logging_mixin.py:115} INFO - [2024-12-04 11:32:45,088] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:32:45,089] {logging_mixin.py:115} INFO - [2024-12-04 11:32:45,089] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:32:45,262] {logging_mixin.py:115} INFO - [2024-12-04 11:32:45,261] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:32:45,265] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:32:45,284] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.927 seconds
[2024-12-04 11:33:17,252] {processor.py:153} INFO - Started process (PID=5588) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:33:17,253] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:33:17,253] {logging_mixin.py:115} INFO - [2024-12-04 11:33:17,253] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:33:17,959] {logging_mixin.py:115} INFO - [2024-12-04 11:33:17,959] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:33:17,959] {logging_mixin.py:115} INFO - [2024-12-04 11:33:17,959] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:33:18,132] {logging_mixin.py:115} INFO - [2024-12-04 11:33:18,131] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:33:18,135] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:33:18,155] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.906 seconds
[2024-12-04 11:33:50,397] {processor.py:153} INFO - Started process (PID=5642) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:33:50,397] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:33:50,398] {logging_mixin.py:115} INFO - [2024-12-04 11:33:50,398] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:33:51,135] {logging_mixin.py:115} INFO - [2024-12-04 11:33:51,135] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:33:51,135] {logging_mixin.py:115} INFO - [2024-12-04 11:33:51,135] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:33:51,307] {logging_mixin.py:115} INFO - [2024-12-04 11:33:51,307] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:33:51,310] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:33:51,328] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.935 seconds
[2024-12-04 11:34:24,845] {processor.py:153} INFO - Started process (PID=5697) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:34:24,846] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:34:24,847] {logging_mixin.py:115} INFO - [2024-12-04 11:34:24,846] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:34:25,559] {logging_mixin.py:115} INFO - [2024-12-04 11:34:25,559] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:34:25,559] {logging_mixin.py:115} INFO - [2024-12-04 11:34:25,559] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:34:25,731] {logging_mixin.py:115} INFO - [2024-12-04 11:34:25,730] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:34:25,734] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:34:25,752] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.911 seconds
[2024-12-04 11:35:02,193] {processor.py:153} INFO - Started process (PID=5755) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:35:02,195] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:35:02,196] {logging_mixin.py:115} INFO - [2024-12-04 11:35:02,195] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:35:02,945] {logging_mixin.py:115} INFO - [2024-12-04 11:35:02,945] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:35:02,946] {logging_mixin.py:115} INFO - [2024-12-04 11:35:02,946] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:35:03,118] {logging_mixin.py:115} INFO - [2024-12-04 11:35:03,117] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:35:03,121] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:35:03,141] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.951 seconds
[2024-12-04 11:35:37,577] {processor.py:153} INFO - Started process (PID=5810) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:35:37,579] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:35:37,579] {logging_mixin.py:115} INFO - [2024-12-04 11:35:37,579] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:35:38,310] {logging_mixin.py:115} INFO - [2024-12-04 11:35:38,310] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:35:38,310] {logging_mixin.py:115} INFO - [2024-12-04 11:35:38,310] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:35:38,484] {logging_mixin.py:115} INFO - [2024-12-04 11:35:38,484] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:35:38,487] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:35:38,505] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.932 seconds
[2024-12-04 11:36:13,785] {processor.py:153} INFO - Started process (PID=5867) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:36:13,787] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:36:13,787] {logging_mixin.py:115} INFO - [2024-12-04 11:36:13,787] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:36:14,510] {logging_mixin.py:115} INFO - [2024-12-04 11:36:14,510] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:36:14,510] {logging_mixin.py:115} INFO - [2024-12-04 11:36:14,510] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:36:14,696] {logging_mixin.py:115} INFO - [2024-12-04 11:36:14,696] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:36:14,699] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:36:14,718] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.936 seconds
[2024-12-04 11:36:49,773] {processor.py:153} INFO - Started process (PID=5923) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:36:49,774] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:36:49,774] {logging_mixin.py:115} INFO - [2024-12-04 11:36:49,774] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:36:50,490] {logging_mixin.py:115} INFO - [2024-12-04 11:36:50,490] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:36:50,490] {logging_mixin.py:115} INFO - [2024-12-04 11:36:50,490] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:36:50,662] {logging_mixin.py:115} INFO - [2024-12-04 11:36:50,662] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:36:50,665] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:36:50,683] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.913 seconds
[2024-12-04 11:37:29,355] {processor.py:153} INFO - Started process (PID=5981) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:37:29,357] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:37:29,357] {logging_mixin.py:115} INFO - [2024-12-04 11:37:29,357] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:37:30,087] {logging_mixin.py:115} INFO - [2024-12-04 11:37:30,086] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:37:30,087] {logging_mixin.py:115} INFO - [2024-12-04 11:37:30,087] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:37:30,258] {logging_mixin.py:115} INFO - [2024-12-04 11:37:30,257] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:37:30,261] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:37:30,282] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.929 seconds
[2024-12-04 11:38:00,545] {processor.py:153} INFO - Started process (PID=6025) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:38:00,546] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:38:00,546] {logging_mixin.py:115} INFO - [2024-12-04 11:38:00,546] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:38:01,301] {logging_mixin.py:115} INFO - [2024-12-04 11:38:01,301] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:38:01,301] {logging_mixin.py:115} INFO - [2024-12-04 11:38:01,301] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:38:01,474] {logging_mixin.py:115} INFO - [2024-12-04 11:38:01,474] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:38:01,477] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:38:01,496] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.954 seconds
[2024-12-04 11:38:37,871] {processor.py:153} INFO - Started process (PID=6092) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:38:37,873] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:38:37,873] {logging_mixin.py:115} INFO - [2024-12-04 11:38:37,873] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:38:38,599] {logging_mixin.py:115} INFO - [2024-12-04 11:38:38,599] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:38:38,599] {logging_mixin.py:115} INFO - [2024-12-04 11:38:38,599] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:38:38,772] {logging_mixin.py:115} INFO - [2024-12-04 11:38:38,772] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:38:38,775] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:38:38,794] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.926 seconds
[2024-12-04 11:39:15,208] {processor.py:153} INFO - Started process (PID=6157) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:39:15,210] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:39:15,210] {logging_mixin.py:115} INFO - [2024-12-04 11:39:15,210] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:39:15,927] {logging_mixin.py:115} INFO - [2024-12-04 11:39:15,927] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:39:15,927] {logging_mixin.py:115} INFO - [2024-12-04 11:39:15,927] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:39:16,101] {logging_mixin.py:115} INFO - [2024-12-04 11:39:16,100] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:39:16,104] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:39:16,123] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.918 seconds
[2024-12-04 11:39:51,840] {processor.py:153} INFO - Started process (PID=6223) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:39:51,841] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:39:51,842] {logging_mixin.py:115} INFO - [2024-12-04 11:39:51,842] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:39:52,576] {logging_mixin.py:115} INFO - [2024-12-04 11:39:52,576] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:39:52,576] {logging_mixin.py:115} INFO - [2024-12-04 11:39:52,576] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:39:52,746] {logging_mixin.py:115} INFO - [2024-12-04 11:39:52,745] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:39:52,749] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:39:52,770] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.933 seconds
[2024-12-04 11:40:31,848] {processor.py:153} INFO - Started process (PID=6291) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:40:31,850] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:40:31,850] {logging_mixin.py:115} INFO - [2024-12-04 11:40:31,850] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:40:32,588] {logging_mixin.py:115} INFO - [2024-12-04 11:40:32,588] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:40:32,588] {logging_mixin.py:115} INFO - [2024-12-04 11:40:32,588] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:40:32,764] {logging_mixin.py:115} INFO - [2024-12-04 11:40:32,764] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:40:32,767] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:40:32,787] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.942 seconds
[2024-12-04 11:41:10,332] {processor.py:153} INFO - Started process (PID=6362) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:41:10,334] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:41:10,334] {logging_mixin.py:115} INFO - [2024-12-04 11:41:10,334] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:41:11,053] {logging_mixin.py:115} INFO - [2024-12-04 11:41:11,053] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:41:11,053] {logging_mixin.py:115} INFO - [2024-12-04 11:41:11,053] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:41:11,226] {logging_mixin.py:115} INFO - [2024-12-04 11:41:11,226] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 51, in <module>
    training_model = PythonOperator(task_id='training_model',python_callable=utils.get_trained_model,
AttributeError: module 'utils' has no attribute 'get_trained_model'
[2024-12-04 11:41:11,229] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:41:11,248] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.918 seconds
[2024-12-04 11:41:51,169] {processor.py:153} INFO - Started process (PID=6436) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:41:51,170] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:41:51,171] {logging_mixin.py:115} INFO - [2024-12-04 11:41:51,171] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:41:51,912] {logging_mixin.py:115} INFO - [2024-12-04 11:41:51,912] {utils.py:145} INFO - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-04 11:41:51,912] {logging_mixin.py:115} INFO - [2024-12-04 11:41:51,912] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2024-12-04 11:41:52,086] {logging_mixin.py:115} INFO - [2024-12-04 11:41:52,085] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 37, in <module>
    utils = module_from_file("utils", "/home/airflow/dags/Lead_scoring_training_pipeline/utils.py")
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 26, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/utils.py", line 16, in <module>
    from Lead_scoring_inference_pipeline.constants import *
ModuleNotFoundError: No module named 'Lead_scoring_inference_pipeline'
[2024-12-04 11:41:52,089] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:41:52,108] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.942 seconds
[2024-12-04 11:42:07,233] {processor.py:153} INFO - Started process (PID=6458) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:42:07,234] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:42:07,234] {logging_mixin.py:115} INFO - [2024-12-04 11:42:07,234] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:42:07,241] {logging_mixin.py:115} INFO - [2024-12-04 11:42:07,240] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 8, in <module>
    from Lead_scoring_inference_pipeline.utils import *
ModuleNotFoundError: No module named 'Lead_scoring_inference_pipeline'
[2024-12-04 11:42:07,241] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:42:07,268] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.037 seconds
[2024-12-04 11:42:49,093] {processor.py:153} INFO - Started process (PID=6514) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:42:49,094] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:42:49,095] {logging_mixin.py:115} INFO - [2024-12-04 11:42:49,095] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:42:49,100] {logging_mixin.py:115} INFO - [2024-12-04 11:42:49,099] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 8, in <module>
    from Lead_scoring_inference_pipeline.utils import *
ModuleNotFoundError: No module named 'Lead_scoring_inference_pipeline'
[2024-12-04 11:42:49,100] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:42:49,125] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.035 seconds
[2024-12-04 11:43:21,277] {processor.py:153} INFO - Started process (PID=6561) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:43:21,277] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:43:21,278] {logging_mixin.py:115} INFO - [2024-12-04 11:43:21,278] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:43:21,283] {logging_mixin.py:115} INFO - [2024-12-04 11:43:21,282] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 8, in <module>
    from Lead_scoring_inference_pipeline.utils import *
ModuleNotFoundError: No module named 'Lead_scoring_inference_pipeline'
[2024-12-04 11:43:21,283] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:43:21,306] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.032 seconds
[2024-12-04 11:43:56,365] {processor.py:153} INFO - Started process (PID=6610) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:43:56,367] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:43:56,367] {logging_mixin.py:115} INFO - [2024-12-04 11:43:56,367] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:43:56,373] {logging_mixin.py:115} INFO - [2024-12-04 11:43:56,372] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 8, in <module>
    from Lead_scoring_inference_pipeline.utils import *
ModuleNotFoundError: No module named 'Lead_scoring_inference_pipeline'
[2024-12-04 11:43:56,373] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:43:56,400] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.038 seconds
[2024-12-04 11:44:35,672] {processor.py:153} INFO - Started process (PID=6663) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:44:35,674] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:44:35,674] {logging_mixin.py:115} INFO - [2024-12-04 11:44:35,674] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:44:35,679] {logging_mixin.py:115} INFO - [2024-12-04 11:44:35,679] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 8, in <module>
    from Lead_scoring_inference_pipeline.utils import *
ModuleNotFoundError: No module named 'Lead_scoring_inference_pipeline'
[2024-12-04 11:44:35,680] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:44:35,707] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.038 seconds
[2024-12-04 11:45:07,317] {processor.py:153} INFO - Started process (PID=6710) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:07,318] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:45:07,318] {logging_mixin.py:115} INFO - [2024-12-04 11:45:07,318] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:07,324] {logging_mixin.py:115} INFO - [2024-12-04 11:45:07,323] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 8, in <module>
    from Lead_scoring_inference_pipeline.utils import *
ModuleNotFoundError: No module named 'Lead_scoring_inference_pipeline'
[2024-12-04 11:45:07,324] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:07,351] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.038 seconds
[2024-12-04 11:45:40,568] {processor.py:153} INFO - Started process (PID=6759) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:40,568] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:45:40,569] {logging_mixin.py:115} INFO - [2024-12-04 11:45:40,569] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:40,574] {logging_mixin.py:115} INFO - [2024-12-04 11:45:40,574] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 8, in <module>
    from Lead_scoring_inference_pipeline.utils import *
ModuleNotFoundError: No module named 'Lead_scoring_inference_pipeline'
[2024-12-04 11:45:40,574] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:40,599] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.034 seconds
[2024-12-04 11:45:50,948] {processor.py:153} INFO - Started process (PID=6770) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:50,949] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:45:50,950] {logging_mixin.py:115} INFO - [2024-12-04 11:45:50,950] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:50,959] {logging_mixin.py:115} INFO - [2024-12-04 11:45:50,958] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 36, in <module>
    utils = module_from_file("utils", "/home/airflow/dags/Lead_scoring_inference_pipeline/utils.py")
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 33, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/dags/Lead_scoring_inference_pipeline/utils.py'
[2024-12-04 11:45:50,959] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:45:50,984] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.040 seconds
[2024-12-04 11:46:26,188] {processor.py:153} INFO - Started process (PID=6819) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:46:26,190] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:46:26,190] {logging_mixin.py:115} INFO - [2024-12-04 11:46:26,190] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:46:26,197] {logging_mixin.py:115} INFO - [2024-12-04 11:46:26,197] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 36, in <module>
    utils = module_from_file("utils", "/home/airflow/dags/Lead_scoring_inference_pipeline/utils.py")
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 33, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/dags/Lead_scoring_inference_pipeline/utils.py'
[2024-12-04 11:46:26,197] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:46:26,223] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.037 seconds
[2024-12-04 11:47:09,136] {processor.py:153} INFO - Started process (PID=6877) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:47:09,137] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:47:09,138] {logging_mixin.py:115} INFO - [2024-12-04 11:47:09,138] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:47:09,145] {logging_mixin.py:115} INFO - [2024-12-04 11:47:09,145] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 36, in <module>
    utils = module_from_file("utils", "/home/airflow/dags/Lead_scoring_inference_pipeline/utils.py")
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 33, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/dags/Lead_scoring_inference_pipeline/utils.py'
[2024-12-04 11:47:09,146] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:47:09,172] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.039 seconds
[2024-12-04 11:47:47,108] {processor.py:153} INFO - Started process (PID=6929) to work on /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:47:47,109] {processor.py:641} INFO - Processing file /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py for tasks to queue
[2024-12-04 11:47:47,110] {logging_mixin.py:115} INFO - [2024-12-04 11:47:47,110] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:47:47,117] {logging_mixin.py:115} INFO - [2024-12-04 11:47:47,117] {dagbag.py:321} ERROR - Failed to import: /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 36, in <module>
    utils = module_from_file("utils", "/home/airflow/dags/Lead_scoring_inference_pipeline/utils.py")
  File "/home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py", line 33, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/dags/Lead_scoring_inference_pipeline/utils.py'
[2024-12-04 11:47:47,118] {processor.py:653} WARNING - No viable dags retrieved from /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py
[2024-12-04 11:47:47,144] {processor.py:161} INFO - Processing /home/airflow/dags/Lead_scoring_training_pipeline/lead_scoring_inference_pipeline.py took 0.039 seconds
